### ISSUE TITLE
Chart(s) should have an option(s) to be stable across deployments

### ISSUE THREAD

**Issue by jcogilvie** [wiz-sec/charts#235]
I run in an environment using infra-as-code tooling that prints out the helm template diff, if there is one, and attaches it to a PR for review.  

This requires us to be able to quash certain diffs by implementing an option to stabilize the template across runs of `helm template`.  It could be a random seed, or it could be a flag, but things like this don't work for us out of the box:

```
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "wiz-kubernetes-connector.name" . }}-delete-connector
  ...
  annotations:
    ...
    rollme: {{ randAlphaNum 5 | quote }}
```

This will change on every deployment with no way to suppress.  What that means is every time I make a change to my repo that deploys wiz (which also deploys a bunch of other tooling) wiz shows up in the diff as changed.  

I would like to request the team to see if there's a way to accomplish the goal of this annotation w/o template instability.  For instance, could we hash some other element of the chart instead?
