### ISSUE TITLE
wiz-kubernetes-integration unable to deploy from scratch via ArgoCD using externalSecrets

### ISSUE THREAD

**Issue by juhosyrjanen** [wiz-sec/charts#331]
Hello,

wiz-kubernetes-integration is unable to deploy from scratch with ArgoCD. Reason for this is dependency on secrets in `job/wiz-kubernetes-connector-create-connector`, it will naturally not be able to run without secrets being present. 

With `external-secrets` Kubernetes secrets are not created within the deployment, instead an `ExternalSecret` resource is created which is syncing with external vault and then creating Kubernetes secrets.

 As The Helm template has a dependency to Kubernetes secrets, the deployment fails
 
```
│   Warning  Failed     9s (x2 over 9s)  kubelet            Error: secret "wiz-sa" not found                                                                                      
```

We are deploying Wiz via ArgoCD using Kustomize + Helm:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wiz

resources:
  - namespace.yml
  - secrets.yml

helmCharts:
- name: wiz-kubernetes-integration
  repo: https://charts.wiz.io/
  releaseName: wiz-kubernetes-integration
  namespace: wiz
  valuesFile: values.yml
  version: 0.1.95
 ```
 
`ExternalSecrets` are defined in the `secrets.yml` file. While deploying this manually directly via Kustomize the deployment will work as `ExternalSecrets` are created with `kustomize build --enable-helm | kubectl apply -f -`, with ArgoCD deployment will remain OutOfSync.

Could the chart be improved upon a bit an allow this sort of use case?

**Comment by gvilarino-mitek** [comment]
Hi, 
We run into the exact same issue. Argocd won´t work at first attempt to sync and manual sync attempts need to be done after the ExternalSecret has been created (by argo on the retries).

**Comment by gvilarino-mitek** [comment]
@juhosyrjanen we fixed this by using waves and hooks. Use this on the external secret:
```
...
kind: ExternalSecret
metadata:
  name: ...
  namespace: ...
  annotations:
    argocd.argoproj.io/sync-wave: "-1" # https://argo-cd.readthedocs.io/en/latest/user-guide/sync-waves/#how-do-i-configure-waves
    argocd.argoproj.io/hook: PreSync # Wiz uses a helm hook called pre-install which maps to PreSync phase in argocd
...
```

If you createalso  the ns with the same argocd kustomization, add this to the ns:
```apiVersion: v1
kind: Namespace
metadata:
  name: ...
  annotations:
    argocd.argoproj.io/sync-wave: "-2" # https://argo-cd.readthedocs.io/en/latest/user-guide/sync-waves/#how-do-i-configure-waves
    argocd.argoproj.io/hook: PreSync # Wiz uses a helm hook called pre-install which maps to PreSync in argocd
```

Hope this helps to your case!
