### ISSUE TITLE
Doubts about configuration 

### ISSUE THREAD

**Issue by miltlima** [wiz-sec/charts#332]
Hello Everyone, I have been installed wiz with the follow configuration using unified chart version 0.1.95, but the broker doesn't work 
 

```yaml
    global:
      wizApiToken:
        secret:
          create: false
          name: wiz-api-token
    wiz-kubernetes-connector:
      autoCreateConnector:
        enabled: true
        clusterFlavor: GKE
      broker:
        enabled: true
      wizConnector:
        createSecret: true
        secretName: wiz-connector-autocreated-secret
    wiz-sensor:
      enabled: true
      imagePullSecret:
        create: false
        name: "wiz-sensor-imagepullkey"
    wiz-admission-controller:
      enabled: true
```

Regards!
