### ISSUE TITLE
Remove default GKE specific tolerations

### ISSUE THREAD

**Issue by juhosyrjanen** [wiz-sec/charts#387]
Hello, 

By default the Helm chart adds GKE specific tolerations to Wiz Sensor DaemonSet. This causes issues with EKS based deployments. The following values fix needs to be added in order to have Wiz correctly deploy on EKS.

```
wiz-sensor:
  daemonset:
    tolerations:
      - operator: "Exists"
```

ArgoCD diff shows the change as follows:

<img width="1323" alt="image" src="https://github.com/user-attachments/assets/8a272d44-1f0b-41c4-8713-0662e49068f0">

This default makes using the Helm chart in multi-cloud deployments a bit cumbersome.
