### ISSUE TITLE
Create and maintain a changelog

### ISSUE THREAD

**Issue by pmcgrath-mck** [wiz-sec/charts#471]
As raised in this issue https://github.com/wiz-sec/charts/issues/262 - we have no tags to do a comparison to see what has changed

Would be good if a changelog was also maintained, this way we get visibility into what to expect on a release bump

We recently bumped from chart `wiz-kubernetes-integration` 0.1.136 -> 0.2.2 which
- replaced the `wiz-kubernetes-connector-broker` deployment with the `wiz-agent` deployment
- we did a diff of the helm chart values and the diffs were small, but did not see that a new deployment was being re-created until deployed to a cluster, so we hit issues with affinity/tolerations/resources etc.

Since this is a critical commercial component on our clusters, I think it is reasonable to expect a changelog/tags so we can evaluate what a version upgrade is going to result in

**Comment by pmcgrath-mck** [comment]
Can see what I mentioned above using this values file
```
global:
  wizApiToken:
    clientId: dummyClientId
    clientToken: dummyClientToken

wiz-admission-controller:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-asg
            operator: In
            values:
            - addons
  enabled: true
  tolerations:
  - effect: "NoSchedule"
    key: "addons-asg"
    operator: "Exists"
  wizApiToken:
    secret:
      create: false
```

will see diffs with this - note we used to be able to set node affinity, but with a recent **patch** bump we no longer can, guessing the templating has changed, which we would need to investigate, a change log entry would possibly have prompted us to check this before upgrading

```
$ helm template wiz wiz-sec/wiz-kubernetes-integration -n wiz --version 0.2.48 --values our-values.yaml | yq '. | select(.kind == "Deployment") | {"NAME": .metadata.name, "TOLERATIONS": .spec.template.spec.tolerations, "AFFINITY": .spec.template.spec.affinity }' 
NAME: wiz-wiz-admission-controller
TOLERATIONS:
  - effect: NoSchedule
    key: addons-asg
    operator: Exists
AFFINITY:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-asg
              operator: In
              values:
                - addons

$ helm template wiz wiz-sec/wiz-kubernetes-integration -n wiz --version 0.2.49 --values our-values.yaml | yq '. | select(.kind == "Deployment") | {"NAME": .metadata.name, "TOLERATIONS": .spec.template.spec.tolerations, "AFFINITY": .spec.template.spec.affinity }' 
NAME: wiz-wiz-admission-controller
TOLERATIONS:
  - effect: NoSchedule
    key: addons-asg
    operator: Exists
AFFINITY:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/os
              operator: In
              values:
                - linux
            - key: kubernetes.io/arch
              operator: In
              values:
                - arm64
                - amd64
```
