### ISSUE TITLE
Add the option to use tag@digest or digest instead of tag

### ISSUE THREAD

**Issue by n3s130** [wiz-sec/charts#536]
Hi, I tried to pin the digest to next to the tag for for admission controller but this was not possible since the tag is used to set some labels and only 63 charaters can be used for labels and I got this error:

````
Secret "wiz-admission-controller-cert" is invalid: [metadata.labels: Invalid value: "2.7@sha256:de9e6acda35749df2c12705dca5df0abb7d511c14ff0707fab78f62928516569": must be no more than 63 characters, metadata.labels: Invalid value: "2.7@sha256:de9e6acda35749df2c12705dca5df0abb7d511c14ff0707fab78f62928516569": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')]
````

I would like to be able to make a deployment using digest. Could you please add that possibility?

**Comment by ofirc-wiz** [comment]
Could you please add an example for a `values.yaml` file?

**Comment by n3s130** [comment]
Sure, like this:

```
image:
  registry: wiziopublic.azurecr.io/wiz-app
  repository: wiz-admission-controller
  tag: 2.7@sha256:de9e6acda35749df2c23816dca5df0abb7d511c14ff0707fab78f62928516569
```

Or:

````
image:
  registry: wiziopublic.azurecr.io/wiz-app
  repository: wiz-admission-controller
  tag: 2.7
  digest: sha256:de9e6acda35749df2c23816dca5df0abb7d511c14ff0707fab78f62928516569
````
