### ISSUE TITLE
Please adhere to least privilege in your RBAC

### ISSUE THREAD

**Issue by act-mreeves** [wiz-sec/charts#93]
The privs should be enumerated instead of being a wildcard because if I understand correctly this can read all secrets. You do probably need to read secrets in your own namespace though. 
https://github.com/wiz-sec/charts/blob/master/wiz-kubernetes-connector/templates/service-account-cluster-reader.yaml#L38-L41
```
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
```

Example by datadog:
https://github.com/DataDog/helm-charts/blob/main/charts/datadog/templates/cluster-agent-rbac.yaml#L9-L21
```
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - pods
  - nodes
  - namespaces
  - componentstatuses
  verbs:
  - get
  - list
  - watch
```

Also if possible please give an example of how to setup a secret out of band so it's not managed by the helm chart so you don't need to pass in the client_id and client_secret via a values file when you first install the helm chart.
```
wizApiToken:
  clientId: ""
  clientToken: ""
  clientEndpoint: ""

broker:
  enabled: true/false

autoCreateConnector:
 connectorName: ""
 apiServerEndpoint: "" # This is only required if broker.enabled = false
 clusterFlavor: ""
```

Thanks!
