### ISSUE TITLE
Mismatched logic between wiz-broker and wiz-connector-creator if `usePodCustomEnvironmentVariablesFile` is used.

### ISSUE THREAD

**Issue by TheAlanNix** [wiz-sec/charts#94]
The wiz-broker and wiz-connector-creator have mismatched logic blocks when service account ID and secret are passed through an environment variables file:

- wiz-broker: https://github.com/wiz-sec/charts/blob/master/wiz-kubernetes-connector/templates/wiz-broker-deployment.yaml#L63-L75
- wiz-connector-creator: https://github.com/wiz-sec/charts/blob/master/wiz-kubernetes-connector/templates/job-create-connector.yaml#L79-L90

If a user were to provide the following values:
```
wizApiToken:
  secret:
    create: false
  
  # API token should be read from an environment file, which is specified in podCustomEnvironmentVariablesFile
  usePodCustomEnvironmentVariablesFile: true
```

Then passing the correct volumes and volume mounts through to both the connector-creator and broker:
```
  customVolumes:
    - name: wiz-kubernetes-connector-secrets
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "wiz-kubernetes-connector-secrets"
  customVolumeMounts:
    - mountPath: "/etc/wiz-secrets/secrets.conf"
      subPath: secrets.conf
      name: wiz-kubernetes-connector-secrets
```

This will result in the broker referencing a secret that does not exist. `Error: secret wiz-kubernetes-connector-api-token not found`

The wiz-connector-creator will complete successfully.
